change_flight_mode.py: Use the updated constant
bluerobotics/ardusub-gitbook pull request #247
Opened 2022-05-01 12:51 UTC by refeed

Closes https://github.com/bluerobotics/ardusub-gitbook/issues/245

2022-05-01 14:52 UTC, ES-Alexander approved these changes
The example probably needs a larger revision to avoid endlessly blocking if the autopilot sends a NACK or never receives the message, in which case it could also be useful to include retries (on ACK timeout). Those points aren’t critical though, and can be handled when the pymavlink examples get [transferred over to ArduSub-Zola](https://github.com/bluerobotics/ardusub-gitbook/issues/230).

More generally, it’s best if commit messages include an indication of which directory a change is occurring in, or the topic it refers to (e.g. in this case we’d normally have `pymavlink: ` at the start of the message), but given the file name is provided it’s not vital this time.

If you’d like to make some changes given that feedback then feel free, but otherwise it can be merged as is :-)

2022-05-01 14:52 UTC, ES-Alexander commented on developers/pymavlink/change_flight_mode.py
>      # Check if command in the same in `set_mode`
```suggestion
    # Check if acknowledged command is not `set_mode`
```

2022-05-01 15:17 UTC, refeed commented
Agreed, I also think it's necessary to put the code that is able to avoid endless blocking.. For now, I can only put a note on the example code about that to notify pymavlink users that that case is possible

2022-05-01 15:28 UTC, ES-Alexander requested changes

2022-05-01 15:28 UTC, ES-Alexander commented on developers/pymavlink/change_flight_mode.py
> +        # if the autopilot sends a NACK or never receives the message
This comment should be up at line 38 where the blocking receive actually occurs.

2022-05-02 13:43 UTC, ES-Alexander approved these changes
Looks good - thanks! :-)

2022-05-02 13:45 UTC, merged