README: Add information about BlueOS
bluerobotics/ardusub-gitbook pull request #257
Opened 2024-09-12 14:49 UTC by patrickelectric

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

2024-09-13 20:06 UTC, ES-Alexander requested changes
Not sure if these docs even still deploy, but 🤷‍♂️

2024-09-13 20:06 UTC, ES-Alexander commented on quick-start/installing-companion.md
> +> **Warning** If you are using BlueOS, please follow the [new documentation](https://blueos.cloud/docs).
```suggestion
> ⚠️ **Warning** ⚠️ The ArduSub Companion software is no longer being developed or supported. New projects and vehicles are recommended to use [BlueOS](https://blueos.cloud/docs/blueos/latest/) instead.
```

2024-09-13 20:06 UTC, ES-Alexander commented on README.md
> +> **Warning** If you are using BlueOS, please follow the [new documentation](https://blueos.cloud/docs).
```suggestion
> ⚠️ **Warning** ⚠️ The Companion onboard computer software is no longer being developed or supported. New projects and vehicles are recommended to use [BlueOS](https://blueos.cloud/docs/blueos/latest/) instead.
```

2024-12-11 08:45 UTC, patrickelectric commented
ping @ES-Alexander

2024-12-11 10:29 UTC, ES-Alexander requested changes
The docs links changed. The current ones do redirect, but to a not great place right now (which we're planning to fix, but may as well go to a better place by default).

Feel free to merge after updating the links :-)

2024-12-11 10:29 UTC, ES-Alexander commented on README.md
> +> ⚠️ **Warning** ⚠️ The Companion onboard computer software is no longer being developed or supported. New projects and vehicles are recommended to use [BlueOS](https://blueos.cloud/docs/blueos/lates
```suggestion
> ⚠️ **Warning** ⚠️ The Companion onboard computer software is no longer being developed or supported. New projects and vehicles are recommended to use [BlueOS](https://blueos.cloud/docs/latest/usage/overview/) instead.
```

2024-12-11 10:29 UTC, ES-Alexander commented on quick-start/installing-companion.md
> +> ⚠️ **Warning** ⚠️ The ArduSub Companion software is no longer being developed or supported. New projects and vehicles are recommended to use [BlueOS](https://blueos.cloud/docs/blueos/latest/) inste
```suggestion
> ⚠️ **Warning** ⚠️ The ArduSub Companion software is no longer being developed or supported. New projects and vehicles are recommended to use [BlueOS](https://blueos.cloud/docs/blueos/latest/) instead.
```
```suggestion
> ⚠️ **Warning** ⚠️ The ArduSub Companion software is no longer being developed or supported. New projects and vehicles are recommended to use [BlueOS](https://blueos.cloud/docs/latest/) instead.
```

2025-04-08 09:22 UTC, ES-Alexander commented
Superseded by #259

2025-04-08 09:22 UTC, closed without merging